### PR TITLE
Emit an event when user select an option by cliking on it

### PR DESCRIPTION
**Pull request by gabrielrobert**
This would be very useful to be able to bind some actions when a user manually select an option by clicking on it.

### CODE REVIEW

**Comment by paliari** [comment]
In this case you can use the `@input` event.

```html
v-autocomplete(:items="items" v-model='item', :get-label='getLabel', :min-len='0' @update-items='update', :component-item='tpl', input-class="test-css-class", @input="itemSelected")
```

**Comment by gabrielrobert** [comment]
@paliari The @input event is triggered every time something is entered in the field.

Take a look:

```
input.v-autocomplete-input(type='search'
      v-model='searchText',
      :placeholder='placeholder',
      :class="inputClass"
      @blur='blur',
      @focus='focus',
      @input='inputChange'
    )
```

@input is calling `inputChange`. Then `inputChange` is calling `onSelectItem` each time.

```
inputChange () {
      this.showList = true
      this.onSelectItem(null)
      utils.callUpdateItems(this.searchText, this.updateItems)
      this.$emit('change', this.searchText)
    },
```

Finally, `onSelectItem` emit the event everytime:

```
onSelectItem (item) {
      if (item) {
        this.internalItems = [item]
        this.searchText = this.getLabel(item)
      } else {
        this.setItems(this.items)
      }
      this.$emit('input', item)
    }
```


This is problematic. I want to be able to do AJAX when user click the selection, I don't want it to be triggered every time something is entered in the field.

**Review by paliari — CHANGES_REQUESTED** [review]
Change event name to "item-selected"

**Comment by gabrielrobert** [comment]
@paliari Done!

**Comment by paliari** [comment]
@gabrielrobert changed plugin behavior. I changed the minor version.
See the docs.

**Comment by gabrielrobert** [comment]
@paliari Perfect, have a nice day!

**Comment by adrianomm06** [comment]
When I select an option it runs twice the method. Why is that?

` <v-autocomplete
                :items="racquets"
                @focus="if(!racquet_product) { racquet_product = null }"
                @item-selected="saveRacquet"
                @update-items="getRacquets2"
                v-model="racquet_product"
                :get-label="getProductLabel2"
                :auto-select-one-item="false"
                :component-item="productTemplate2"
                :min-len="3"
                :wait="200"
                placeholder="Type Racquet Name">
        </v-autocomplete>`

in the netowrk appear twice the ajax:

saveracquetinservice?service_id=53&product_id=158
saveracquetinservice?service_id=53&product_id=158

**Pull request merged**
